postfix_relay_hostname:      "relay01.int.example"

# Appliance(s) allowed to send mail in the clear
postfix_relay_mynetworks:
  - "127.0.0.0/8"
  - "10.10.20.15"

# Provider (smarthost) parameters
postfix_smarthost:          "smtp.mail.cloud.local"
postfix_smarthost_port:     25          # 25, 587 (STARTTLS) or 465 (implicit TLS)
postfix_smarthost_tls_mode: wrapper   # values: starttls | wrapper
postfix_smarthost_user:     "customer-123"
postfix_smarthost_pass:     "S3cr3t!"   # **Use Ansible Vault in real life**

# TLS behaviour: "encrypt" = require STARTTLS, "may" = opportunistic
postfix_tls_security_level: "encrypt"

# Default CA bundle for smarthost TLS verification
postfix_smarthost_ca_file: "/etc/ssl/certs/ca-bundle.crt"

# Skip TLS verification for the smarthost connection
postfix_smarthost_tls_skip_verify: false

# Path on the relay server for a custom CA certificate for smarthost TLS verification
postfix_smarthost_custom_ca_file_path: "" # e.g., "/etc/postfix/custom_smarthost_ca.crt"

# Content of the custom CA certificate (PEM format) for smarthost TLS verification
# If provided, this content will be deployed to postfix_smarthost_custom_ca_file_path
postfix_smarthost_custom_ca_content: ""

# Packages (override if you prefer exim/sendmail)
postfix_packages:
  - postfix
  - cyrus-sasl
  - cyrus-sasl-plain
